apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import register, profile, stats, login_register, CheckTokenUploadView, UploadCreateView, UploadDetailView, VotoCreateView, CheckTokenView, UploadListView, UploadAllListView

app_name = "users"

urlpatterns = [
    path('register/', register, name='register'),
    path('stats/', stats, name='stats'),
    path('profile/', profile, name='profile'),
    path('upload/', UploadCreateView.as_view(), name='upload'),
    path('upload/<int:pk>/', UploadDetailView.as_view(), name='detail'),
    path('', UploadAllListView.as_view(), name='list-all'),
    path('list/<int:user_id>', UploadListView.as_view(), name='list'),
    # path('voto/<int:upload_id>/', VotoCreateView.as_view(), name='voto'),
    path('check-token/', CheckTokenView.as_view(), name='check-token'),
    path('check-token-upload/', CheckTokenUploadView.as_view(), name='check-token-upload'),
    path('login_register/', login_register, name='login-register'),
    path(
        'login',
        LoginView.as_view(
            template_name='users/login.html',
            redirect_authenticated_user=True
        ),
        name='login'
    ),
    path('logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:list-all')
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:login')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    )
]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media files

apps/users/forms.py
from django import forms
from .models import User, Profile, Upload, Voto
from django.utils.safestring import mark_safe
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()
    aceito = forms.BooleanField(widget=forms.CheckboxInput(),
                           label=mark_safe('Aceito a <a class="x" href="https://www.vorwerk.com/pt/pt/c/home/geral/politica-de-privacidade" target="_blank">Política de Privacidade</a>'))

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name', 'aceito', 'role']
        help_texts = {
            'password1': '',
            'password2': ''
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['password1'].required = False
        self.fields['password2'].required = False
        self.fields['password1'].widget.attrs['hidden'] = True
        self.fields['password2'].widget.attrs['hidden'] = True
        self.fields['password1'].label = ''
        self.fields['password2'].label = ''
        self.fields['password1'].help_text = ''
        self.fields['password2'].help_text = ''
        self.fields['email'].label = 'E-mail'
        self.fields['aceito'].required = True
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if email and User.objects.filter(email=email).exclude(username=username).count():
            raise forms.ValidationError(("Este e-mail já se encontra registado."))
        return email
    
    def clean_username(self):
        email = self.cleaned_data.get('email')
        username = self.cleaned_data.get('username')
        if username and User.objects.filter(username=username).exclude(email=email).count():
            raise forms.ValidationError(("O nome de utilizador que escolheu já se encontra registado."))
        return username


class ProfileRegisterForm(forms.ModelForm):
    class Meta:
        model = Profile
        fields = ['user']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['user'].required = False


class UserUpdateForm(forms.ModelForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['email', 'username', 'first_name', 'last_name']
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['first_name'].required = True
        self.fields['last_name'].required = True


class UploadForm(forms.ModelForm):
    class Meta:
        model = Upload
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        user_id = kwargs.pop('user_id')
        super().__init__(*args, **kwargs)
        self.initial['user'] = User.objects.get(id=user_id)
    
    def clean_email(self):
        email = self.cleaned_data.get('email')
        if email and Upload.objects.filter(email=email).count():
            raise forms.ValidationError(("Este e-mail já está associado a uma participação. Tente novamente."))
        return email


class VotoForm(forms.ModelForm):
    class Meta:
        model = Voto
        fields = '__all__'
    
    def __init__(self, *args, **kwargs):
        upload_id = kwargs.pop('upload_id')
        super().__init__(*args, **kwargs)
        self.initial['upload'] = Upload.objects.get(id=upload_id)

apps/users/views.py
import jwt
from django.db.models.query import QuerySet
from django.db.models import Count, Q
from typing import Any, Dict
from django.shortcuts import render, redirect
from django.contrib import messages
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth.views import PasswordResetCompleteView, PasswordResetDoneView
from django.contrib.auth.decorators import login_required
from django.views.generic import CreateView, DetailView, TemplateView, ListView
from django.urls import reverse_lazy, reverse
from django.conf import settings
from .models import Profile, User, Upload, Voto
from .forms import UserRegisterForm, UserUpdateForm, ProfileRegisterForm, UploadForm, VotoForm
from .roles import role_required, ADMIN
from django.conf import settings
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import get_object_or_404
from django_filters.views import FilterView
from .filters import UploadFilter



def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data.get('email')
            reset_password_form = PasswordResetForm(data={'email': email})
            if reset_password_form.is_valid():
                reset_password_form.save(request=request,
                    email_template_name='users/password_define_email.txt',
                    html_email_template_name='users/password_define_email.html')
                messages.success(request,
                    f'Conta criada com sucesso. Consulte a caixa de correio {email} para definir a palavra-passe')
                return redirect('users:login')
            else:
                messages.error(request,
                    'Problemas com o envio de email para definir a password...')
            return redirect('users:login')
        else:
            messages.error(request,
                'Problemas com a criação de conta. Ver informação em baixo...')
    else:
        form = UserRegisterForm()
    return render(request, 'users/register.html', {'form': form})


@login_required
def profile(request):
    if request.method == 'POST':
        u_form = UserUpdateForm(request.POST, instance=request.user)
        if u_form.is_valid():
            u_form.save()
            messages.success(request, 'A tua conta foi atualizada!')
            return redirect('users:profile')
        else:
            messages.error(request,
                'Problemas a atualizar a tua conta, vê os erros em baixo...')
    else:
        u_form = UserUpdateForm(instance=request.user)
    context = {
        'u_form': u_form,
    }
    return render(request, 'users/profile.html', context)


def login_register(request):
    return render(request, 'users/login_register.html')


class MyPasswordResetCompleteView(PasswordResetCompleteView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.success(request, 'A sua palavra-passe foi definida com sucesso \
            Faça o login agora.')
        return redirect('users:login')

class MyPasswordResetDoneView(PasswordResetDoneView):
    def dispatch(self, request, *args, **kwargs):
        response = super().dispatch(request, *args, **kwargs)
        messages.success(request, 'Um e-mail acabou de ser enviado com as \
            instruções para redefinir a sua senha... Confirme, por favor.')
        return redirect('users:login')

class UploadCreateView(CreateView):
    model = Upload
    form_class = UploadForm

    def get(self, request):
        self.user_id = request.user.id
        return super().get(request)

    def post(self, request):
        self.user_id = request.user.id
        return super().post(request)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['user_id'] = self.user_id
        return kwargs

    def get_success_url(self):
        messages.success(self.request, f'Participação Submetida! Deverá consultar o e-mail "{self.object.email}" para validar a participação!')
        return reverse(
            'users:list',
            kwargs={
                'user_id': self.user_id
            })


class UploadDetailView(DetailView):
    model = Upload
    template_name = 'users/detail.html'

    def get_context_data(self, **kwargs: Any):
        ctx = super().get_context_data(**kwargs)
        votos = Voto.objects.filter(upload = self.object.id,validade=True).count()
        ctx['votos'] = votos
        return ctx

class UploadListView(FilterView, ListView):
    model = Upload
    filterset_class = UploadFilter
    template_name = 'users/list.html'

    def get(self,request, user_id):
        self.user_id = request.user.id
        return super().get(request)

    def get_queryset(self):
        return Upload.objects.filter(user=self.user_id, ativo=True).annotate(votos=Count("voto", filter=Q(voto__validade=True)))
    
    def get_context_data(self, **kwargs: Any):
        ctx = super().get_context_data(**kwargs)
        return ctx


class UploadAllListView(FilterView,ListView):
    model = Upload
    filterset_class = UploadFilter
    template_name = 'users/list.html'

    def get_queryset(self):
        return Upload.objects.filter(ativo=True).annotate(votos=Count("voto", filter=Q(voto__validade=True)))


class VotoCreateView(CreateView):
    model = Voto
    form_class = VotoForm

    def get(self,request, upload_id):
        self.upload_id = upload_id
        return super().get(request)

    def post(self,request, upload_id):
        self.upload_id = upload_id
        return super().post(request)

    def get_form_kwargs(self, *args, **kwargs):
        kwargs = super().get_form_kwargs()
        kwargs['upload_id'] = self.upload_id
        return kwargs
    
    def get_success_url(self):
        messages.success(self.request, 'Voto Submetido! Deverá consultar o seu e-mail para validar o voto!')
        return reverse(
            'users:detail',
            kwargs={
                'pk': self.upload_id
            })

class CheckTokenView(TemplateView):
    def get(self, request, *args, **kwargs):
        token = self.request.GET.get('token')
        if token:
            try:
                decoded_token = jwt.decode(token, settings.SECRET_KEY, algorithms=['HS256'])
                vote_id = decoded_token['vote_id']
                voto = Voto.objects.get(id=vote_id)
                if voto.validade:
                    messages.success(self.request, 'Voto já foi Validado!')
                else:
                    messages.success(self.request, 'Voto Validado!')
                    Voto.objects.filter(id=vote_id).update(validade=True)
                upload_id = decoded_token['upload_id']
                redirect_url = reverse('users:detail', kwargs={'pk': upload_id})
                return redirect(redirect_url)
            except jwt.ExpiredSignatureError:
                message = 'Token expirado.'
                messages.error(self.request, message)
                redirect_url = reverse('users:login')
                return redirect(redirect_url)
            except jwt.InvalidTokenError:
                message = 'Token inválido.'
                messages.error(self.request, message)
                redirect_url = reverse('users:login')
                return redirect(redirect_url)
        else:
            message = 'Nenhum Token encontrado.'
            messages.warning(self.request, message)
            redirect_url = reverse('users:login')
            return redirect(redirect_url)
        
        
class CheckTokenUploadView(TemplateView):
    def get(self, request, *args, **kwargs):
        token = self.request.GET.get('token')
        if token:
            try:
                decoded_token = jwt.decode(token, settings.SECRET_KEY, algorithms=['HS256'])
                upload_id = decoded_token['upload_id']
                upload = Upload.objects.get(id=upload_id)
                if upload.ativo:
                    messages.success(self.request, 'Upload já foi Validado!')
                else:
                    messages.success(self.request, 'Upload Validado!')
                    Upload.objects.filter(id=upload_id).update(ativo=True)
                redirect_url = reverse('users:list-all')
                return redirect(redirect_url)
            except jwt.ExpiredSignatureError:
                message = 'Token expirado.'
                messages.error(self.request, message)
                redirect_url = reverse('users:login')
                return redirect(redirect_url)
            except jwt.InvalidTokenError:
                message = 'Token inválido.'
                messages.error(self.request, message)
                redirect_url = reverse('users:login')
                return redirect(redirect_url)
        else:
            message = 'Nenhum Token encontrado.'
            messages.warning(self.request, message)
            redirect_url = reverse('users:login')
            return redirect(redirect_url)

@login_required
def stats(request):
    uploads = Upload.objects.all().count()
    uploads_validos = Upload.objects.filter(ativo=True).count()
    votos = Voto.objects.all().count()
    votos_validos = Voto.objects.filter(validade=True).count()
    return render(request, 'users/stats.html', context={'uploads':uploads,'uploads_validos':uploads_validos,'votos':votos,'votos_validos':votos_validos})

apps/users/templates/users/detail.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <div class="row align-items-center">
                <div class="col-12 col-lg-6">
                    <img style="max-height: 600px;" src="{{object.imagem.url}}" alt="Imagem Avental" width="100%">
                </div>
                <div class="my-4 col-12 col-lg-6">
                    <h3 class="p-2">{{ object.first_name }} {{ object.last_name }}</h3>
                    <h5 class="p-2">Votos: {{votos}}</h5>
                    <!-- <a class="m-2 btn btn-outline-info" href="{% url 'users:voto' object.id %}">Votar</a> -->
                    <br>
                    <br>
                    <h5 class="m-2" style="border-bottom: 1px solid black;">Partilhe</h5>
                    <div class="m-2">
                        <a class="mr-2" style="font-size: 35px;" href="https://api.whatsapp.com/send?text=https://passatempo.bimby.pt/upload/{{object.id}}" target="_blank"><i class="fab fa-whatsapp"></i></a>
                        <a class="mr-2" style="font-size: 35px;" href="https://www.facebook.com/sharer.php?u=passatempo.bimby.pt/upload/{{object.id}}" target="_blank" rel="noopener"><i class="fab fa-facebook"></i></a>
                        <a class="mr-2" style="font-size: 35px;" href="https://twitter.com/intent/tweet?text=%20passatempo.bimby.pt/upload/{{object.id}}" target="_blank" rel="noopener"><i class="fab fa-twitter"></i></a>
                        <a class="mr-2" style="font-size: 35px;" href="https://www.linkedin.com/sharing/share-offsite/?url=https%3A%2F%2Fpassatempo.bimby.pt/upload/{{object.id}}" target="_blank" rel="noopener"><i class="fab fa-linkedin"></i></a>
                        <a class="mr-2" style="font-size: 35px;" href="mailto:?subject=Votação Passatempo Bimby®&body=https://passatempo.bimby.pt/upload/{{object.id}}"><i class="fas fa-envelope"></i></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content%}

apps/users/templates/users/list.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div style="margin-left: -16px; margin-right: -16px;">
    <img src="{% static 'images/vencedor.jpg' %}" width="100%" alt="">
</div>
<div style="background-color: white; padding: 10px; margin: 20px; margin-bottom: 0px;margin-top: 30px; border-top-right-radius: 10px; border-top-left-radius: 10px;" class="row align-items-end">
    <div class="col-6">
        <h3>Pesquisa</h3>
    </div>
    <div class="col-6" style="text-align: right;">
        <a class="btn btn-md mt-1 mb-1" data-toggle="collapse" href="#collapseExample" role="button" aria-expanded="false" aria-controls="collapseExample"><i class="fas fa-search"></i></a>
    </div>
</div>
<div class="collapse" id="collapseExample">
<!-- <div> -->
    <!-- <div style="margin: 50px; margin-top: 20px; margin-bottom: 0px; border-radius: 10px;" class="card card-body"> -->
    <div style="margin: 20px; margin-top: 0px; margin-bottom: 0px; border-radius: 10px; border-top-right-radius: 0px; border-top-left-radius: 0px;" class="card card-body">
        <div>
            <form action="" method="get" class="form">
                <div class="row">
                    <div class="col-12 col-lg-4">
                        {{ filter.form.email|as_crispy_field  }}
                    </div>
                    <div class="col-12 col-lg-4">
                        {{ filter.form.first_name|as_crispy_field  }}
                    </div>
                    <div class="col-12 col-lg-4">
                        {{ filter.form.last_name|as_crispy_field  }}
                    </div>
                </div>   
                <button class='btn btn-md mt-1 mb-1' type="submit">Pesquisar</button>
            </form>
        </div>
    </div>
</div>
<div class="row" style="padding:20px; padding-top: 40px;">
    {% for object in object_list %}
    <div class="col-lg-3 col-md-4 col-sm-6 d-none d-sm-block" style="margin-bottom: 30px;">
        <div class="card heroimgbox">
            <img class="card-img-top heroimg" src="{{object.imagem.url}}" alt="Card image cap" height="350px">
            <div class="card-body">
                <h5 class="card-title">{{object.first_name}} {{object.last_name}}</h5>
                <p class="card-text">Votos: {{object.votos}}</p>
                <!-- <a href="{% url 'users:detail' object.id %}" class="btn btn-primary">ver</a> -->
            </div>
        </div>
    </div>
    <div class="col-12 d-block d-sm-none" style="margin-bottom: 30px;">
        <div class="card heroimgbox">
            <img class="card-img-top heroimg" src="{{object.imagem.url}}" alt="Card image cap">
            <div class="card-body">
                <h5 class="card-title">{{object.first_name}} {{object.last_name}}</h5>
                <p class="card-text">Votos: {{object.votos}}</p>
                <!-- <a href="{% url 'users:detail' object.id %}" class="btn btn-primary">ver</a> -->
            </div>
        </div>
    </div>
    {% endfor %}
</div>
{% endblock content %}

apps/users/templates/users/login_register.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="row">
	<div class="col-12 col-md-8 offset-md-2">
		<div class="heroimgbox-login p-4 my-5">
            <h5 class="text-center">Ainda não se registou?</h5>
            <div class="text-center mb-4">
                <a class="btn" href="{% url 'users:register' %}">Registar</a>
            </div>
            <h5 class="text-center">Já está registado?</h5>
            <div class="text-center">
                <a class="btn" href="{% url 'users:login' %}">Iniciar Sessão</a> <br>
            </div>
		</div>
	</div>
</div>
{% endblock %}

apps/users/templates/users/logout.html
{% extends "base.html" %}
{% block content %}
    <h2>Acabou de terminar sessão...</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Fazer Login outravez..</a>
        </small>
    </div>
{% endblock content%}

apps/users/templates/users/password_define_email.html
<!-- <p>
    Acabou de receber este mail, depois da sua conta ter sido criada com o endereço: {{ user.email }}...
    Para definir a senha, clique <a href="{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">AQUI</a>.
</p>
<p>Se não sabe a razão de ter recebido este e-mail, ignore, por favor.</p> -->
<p>Olá,</p>
<p>Está a receber este e-mail porque criou uma conta com e-mail {{ user.email }} no site <a href="https://passatempo.bimby.pt">passatempo.bimby.pt</a>. Para definir a palavra-passe, <a href="{{ protocol}}://{{ domain }}{% url 'users:password_reset_confirm' uidb64=uid token=token %}">clique aqui</a>.</p>
<p>Se não sabe a razão de ter recebido este e-mail, ignore, por favor.</p>
<p>Obrigada,<br>
Equipa Bimby®
</p>

apps/users/templates/users/password_reset.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 mt-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4">Recuperar Palavra-Passe</legend>
                    {{ form|crispy }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Pedir Palavra-Passe</button>
                </div>
            </form>
        </div>
    </div> 
</div>
{% endblock content%}

apps/users/templates/users/password_reset_complete.html
{% extends "base.html" %}
{% block content%}
    <div class="alert alert-info">
        A sua palavra-passe foi definida.
    </div>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'users:login' %}">Inicie sessão aqui</a>
        </small>
    </div>
{% endblock content%}

apps/users/templates/users/password_reset_done.html
{% extends "base.html" %}

{% block content%}
    <div class="alert alert-info mt-4">
        Um e-mail foi enviado com as instruções para definir a sua Palavra-passe... Confirme, por favor.
    </div>
{% endblock content%}

apps/users/templates/users/profile.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <div class="media">
                <div class="media-body">
                    <h2 class="account-heading">{{ user.first_name }} {{ user.last_name }}</h2>
                    <p class="text-secondary">{{ user.email }}</p>
                </div>
            </div>
            <form method="POST" enctype="multipart/form-data">
                <!-- 'enctype' to suport images in the form -->
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #23282A;">Informação de Perfil</legend>
                        <div class="row">
                            <div class="col-12">
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        {{ u_form.email|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        {{ u_form.username|as_crispy_field }}
                                    </div>
                                </div>
                                <div class="row">
                                    <div class="col-12 col-md-6">
                                        {{ u_form.first_name|as_crispy_field }}
                                    </div>
                                    <div class="col-12 col-md-6">
                                        {{ u_form.last_name|as_crispy_field }}
                                    </div>
                                </div>
                            </div>
                        </div>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Atualizar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content%}

apps/users/templates/users/register.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<style>
    .x {
        color: #23282A;
    }
</style>
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <form method="POST">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #23282A;"><i style="width: 30px" class="fa-solid fa-user-plus"></i>Registo</legend>
                    <div class="row">
                        <div class="col-12">
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.email|as_crispy_field }}
                                </div>
                                <div class="col-12 col-md-6">
                                    {{ form.username|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.first_name|as_crispy_field }}
                                </div>
                                <div class="col-12 col-md-6">
                                    {{ form.last_name|as_crispy_field }}
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                </div>
                            </div>
                            <div class="row">
                                <div class="col-12 col-md-6">
                                    {{ form.aceito|as_crispy_field }}
                                    {{ form.role.as_hidden }}
                                </div>
                            </div>
                        </div>
                    </div>
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Registar</button>
                </div>
            </form>
            <div class="pb-2">
                <p class="text-muted">
                    Já se registou? <a href="{% url 'users:login' %}" style="color: #23282A;">Inicie sessão aqui</a>
                </p>
            </div>
            <!-- <div class="border-top pt-3">
                <small class="text-muted">
                    Already Have An Account? <a class="ml-2" href="{% url 'users:login' %}">Sign In</a>
                </small>
            </div> -->
        </div>
    </div>
</div>
{% endblock content%}

apps/users/templates/users/stats.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<style>
    .card{
        margin: 55px;
    }

    .card-text{
        font-size: 70px;
    }
</style>
<div class="row">
    <div class="col-5 card text-center" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Uploads</h5>
        <p class="card-text">{{uploads}}</p>
        </div>
    </div>
    <div class="col-5 card text-center" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Uploads Válidos</h5>
        <p class="card-text">{{uploads_validos}}</p>
        </div>
    </div>
    <div class="col-5 card text-center" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Votos</h5>
        <p class="card-text">{{votos}}</p>
        </div>
    </div>
    <div class="col-5 card text-center" style="width: 18rem;">
        <div class="card-body">
        <h5 class="card-title">Votos Válidos</h5>
        <p class="card-text">{{votos_validos}}</p>
        </div>
    </div>
</div>

{% endblock content%}

apps/users/templates/users/upload_form.html
{% extends "base_bg.html" %}
{% load crispy_forms_tags %}

{% block content%}
<div class="row">
    <div class="col-12 col-lg-8 offset-lg-2">
        <div class="heroimgbox-login p-4 my-5">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <fieldset class="form-group">
                    <legend class="border-bottom mb-4" style="color: #23282A;"><i style="width: 30px" class="fa-solid fa-user-plus"></i>Participar</legend>
                    {{ form.user.as_hidden }}
                    {{ form.email|as_crispy_field }}
                    {{ form.first_name|as_crispy_field }}
                    {{ form.last_name|as_crispy_field }}
                    {{ form.imagem|as_crispy_field }}
                </fieldset>
                <div class="form-group">
                    <button class="btn btn-outline-info" type="submit">Enviar</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content%}