apps/users/urls.py
from django.urls import path, reverse_lazy
from django.contrib.auth.views import (
    LoginView, LogoutView, PasswordResetView, PasswordResetDoneView,
    PasswordResetConfirmView, PasswordResetCompleteView
)
from .views import register, profile, stats, login_register, CheckTokenUploadView, UploadCreateView, UploadDetailView, VotoCreateView, CheckTokenView, UploadListView, UploadAllListView

app_name = "users"

urlpatterns = [
    path('register/', register, name='register'),
    path('stats/', stats, name='stats'),
    path('profile/', profile, name='profile'),
    path('upload/', UploadCreateView.as_view(), name='upload'),
    path('upload/<int:pk>/', UploadDetailView.as_view(), name='detail'),
    path('', UploadAllListView.as_view(), name='list-all'),
    path('list/<int:user_id>', UploadListView.as_view(), name='list'),
    # path('voto/<int:upload_id>/', VotoCreateView.as_view(), name='voto'),
    path('check-token/', CheckTokenView.as_view(), name='check-token'),
    path('check-token-upload/', CheckTokenUploadView.as_view(), name='check-token-upload'),
    path('login_register/', login_register, name='login-register'),
    path(
        'login',
        LoginView.as_view(
            template_name='users/login.html',
            redirect_authenticated_user=True
        ),
        name='login'
    ),
    path('logout/',
        LogoutView.as_view(template_name='users/logout.html'),
        name='logout'),
    path(
        'password-reset/',
        PasswordResetView.as_view(
            template_name='users/password_reset.html',
            email_template_name='users/password_reset_email.html',
            success_url=reverse_lazy('users:list-all')
        ),
        name='password_reset'
    ),
    path(
        'password-reset/done',
        PasswordResetDoneView.as_view(
            template_name='users/password_reset_done.html'
        ),
        name='password_reset_done'
    ),
    path(
        'password-reset-confirm/<uidb64>/<token>',
        PasswordResetConfirmView.as_view(
            template_name='users/password_reset_confirm.html',
            success_url=reverse_lazy('users:login')
        ),
        name='password_reset_confirm'
    ),
    path(
        'password-reset-complete',
        PasswordResetCompleteView.as_view(
            template_name='users/password_reset_complete.html'
        ),
        name='password_reset_complete'
    )
]

main/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('apps.users.urls', namespace='users'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # media files

templates/_footer.html
<script type="text/javascript">
    $(document).ready(function () {
        $('#sidebarCollapse').on('click', function () {
            $('#sidebar').toggleClass('active');

            var act = $('#sidebar').hasClass('active');
            if (act) {
                $('#content').css('margin-left','120px');
            }else{
                $('#content').css('margin-left','0px');
            }
            
        });
        $(".table-row").click(function() {
            window.document.location = $(this).data("href");
        });
    });
</script>

templates/_head.html
{% load static %}

<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="IE=edge">

<!-- Bootstrap CSS CDN -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/css/bootstrap.min.css" integrity="sha384-B0vP5xmATw1+K9KRQjQERJvTumQW0nPEzvF6L/Z6nronJ3oUOFUFpCjEUQouq2+l" crossorigin="anonymous">
<!-- Font Awesome -->
<script src="https://kit.fontawesome.com/b92dfff54e.js" crossorigin="anonymous"></script><!-- <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.13.0/css/all.css"> -->

<!-- jQuery CDN - Slim version (=without AJAX) -->
<script src="{% static 'kendo/js/jquery.min.js' %}"></script>
<!-- <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script> -->
<!-- Popper.JS -->
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js" integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous"></script>

<script src="https://cdn.jsdelivr.net/npm/chart.js@3.5.1/dist/chart.min.js"></script>
<!-- Kendo UI-->
<link href="{% static 'kendo/styles/kendo.common-bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'kendo/styles/kendo.bootstrap.min.css' %}" rel="stylesheet">

<script src="{% static 'kendo/js/kendo.all.min.js' %}"></script>
<script src="{% static 'kendo/js/cultures/kendo.culture.pt-PT.min.js' %}"></script>
<script src="{% static 'kendo/js/messages/kendo.messages.pt-PT.min.js' %}"></script>
<script src="{% static 'kendo/js/messages/custom_messages.js' %}"></script>

<style>
    @font-face {
        font-family: Merriweather;
        src: url("{% static 'fonts/Merriweather-Regular.ttf' %}");
    }

    @font-face {
        font-family: Source-Regular;
        src: url("{% static 'fonts/SourceSansPro-Regular.ttf' %}");
    }

    @font-face {
        font-family: Source-Bold;
        src: url("{% static 'fonts/SourceSansPro-Bold.ttf' %}");
    }
</style>

<title>Passatempo Bimby®</title>

templates/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    {% include '_head.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'images/vw.png' %}" type="image/png" sizes="16x16">
    
    {% if not user.is_authenticated %}
    <style>
        @media (max-width: 991px) {
            #navbarSupportedContent {
                margin-top: 16.125em;
            }
        }
    </style>
    {% endif %}
</head>

<body>
    <div class="container-fluid px-0">
        <!-- Top Navbar -->
        <nav class="navbar navbar-expand-lg mx-0 mt-0 px-4 pt-3">
            <a class="navbar-brand ml-2 mr-4" href="{% url 'users:profile' %}"><img src="{% static 'images/vorwerk.png' %}" alt="" style="width: 50%"></a>
            {% if user.is_authenticated %}
                <a class="mr-4 ml-auto d-lg-none" href="{% url 'users:profile' %}">
                    <img class="rounded-circle mr-2 p-1" style="width: 35px; height: 35px;"
                            src="{% static 'images/smiley.png' %}">{{ user.username }}
                </a>
            {% endif %}
            <button class="btn navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <i class="fas fa-bars"></i>
            </button>
          
            <div class="collapse navbar-collapse nav justify-content-lg-center flex-column flex-lg-row p-3 p-lg-0" id="navbarSupportedContent" {% if user.is_authenticated %} style="margin-left: 6rem;" {% else %}style="margin-right: 6rem;" {% endif %}>
                {% if user.is_authenticated %}
                <li class="menu-user d-block d-lg-none">
                    <hr class="d-lg-none" style="border-top: 1px solid white;">
                    <!-- <button onclick="logOut()" class="btn-rev btn-md mr-1"
                        style="padding: 0.5rem 1rem;"><i class="fas fa-power-off"></i>&nbsp; Logout
                    </button> -->
                    <a href="{% url 'users:logout' %}" class="btn-rev btn-md mr-1" style="padding: 0.5rem 1rem;"><i class="fas fa-power-off"></i>&nbsp; Logout</a>
                </li>
                {% endif %}
            </div>

            {% if user.is_authenticated %}
            <a class="d-none d-lg-inline-block mr-1 px-3 py-2 menu-user" href="{% url 'users:profile' %}">
                <img class="rounded-circle mr-2 p-1" src="{% static 'images/smiley.png' %}">{{ user.username }}
            </a>
            <a class="btn btn-md mr-2 d-none d-lg-inline-block" style="padding-left: 12px; padding-right: 12px;" href="{% url 'users:logout' %}"><i class="fas fa-power-off"></i></a>
            <!-- <button onclick="logOut()" class="btn btn-md mr-2 d-none d-lg-inline-block" style="padding-left: 12px; padding-right: 12px;"><i class="fas fa-power-off"></i></button> -->
            {% endif %}
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div>
                {% for message in messages %}
                <div class="text-center mt-4 alert alert-{{ message.tags }}">
                    <i style="font-size: 20px;" class="fas fa-exclamation-circle"></i>
                    {{ message }}
                </div>
                {% endfor %}
                {% block content %}{% endblock %}
            </div>
        </div> 
        
        <!-- Footer d-none d-sm-none d-md-block  -->
        <div class="w-100 footer" style="font-size: 12px;">
            <div class="row p-4 m-0 text-center text-md-left" style="background-color: #d9d9d9;">
                <div class="col-12 col-md-3 mt-1">
                    <h6><a href="https://www.vorwerk.com/pt/pt/c/home/geral/termos-e-condicoes" target="_blank">Termos e Condições</a></h6>
                </div>
                <div class="col-12 col-md-3 mt-1">
                    <h6><a href="https://www.vorwerk.com/pt/pt/c/dam-home/downloads/regulamentos-passatempos/Regulamento-passatempo-o-ar-e-de-todos-2023.pdf" target="_blank">Regulamento</a></h6>
                </div>
                <div class="col-12 col-md-3 mt-1 px-0">
                    <h6>
                        <a href="https://www.vorwerk.com/pt/pt/c/home/geral/politica-de-privacidade" target="_blank">Política de privacidade</a>
                    </h6>
                </div>
                <div class="col-12 col-md-3 mt-4 mt-md-0">
                    <div class="socialmedia d-flex justify-content-around">
                        <a href="https://www.facebook.com/BimbyPortugal?fref=ts" target="_blank"><i class="fab fa-facebook"></i></a>
                        <a href="https://www.instagram.com/bimbyportugal/" target="_blank"><i class="fab fa-instagram"></i></a>
                        <a href="https://www.youtube.com/channel/UCCsNIGpKCR5XfNoYbiZi30g" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a href="https://www.pinterest.pt/bimbyportugal/?eq=bimby&etslf=2543" target="_blank"><i class="fab fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
            <div class="row p-1 m-0" style="background-color: rgb(162, 161, 161);">
                <div class="col mx-auto text-center">
                    <a href="https://qloudyx.pt" target="_blank"> &#169; {% now "Y" %}, eXcellerated by qloudyx.</a>
                </div>
            </div>
        </div>
        
        
    </div>
    {% include '_footer.html' %}
    <script id="jsLogoutTemplate" type="text/x-kendo-template">
        <div>
            <p>{{ user.username }}, pretende terminar sessão?</p>
        </div>
    </script>
    <script>
        var LogOutScripts = (function () {
            // Instance stores a reference to the LogOutScripts
            var instance;
            // Dialog object
            var dialog = $("<div />");

            function init() {
                dialog = dialog.kendoDialog({
                    title: "Terminar sessão",
                    content: kendo.template($("#jsLogoutTemplate").html()),
                    closable: false,
                    buttonLayout: "normal",
                    actions: [
                        {
                            text: "Sim",
                            action: function (e) {
                                window.location.href = "{% url 'users:logout' %}";
                                return true;
                            }
                        },
                        {
                            text: "Não",
                            primary: true,
                            action: function (e) {
                                // Do something...
                                // We must return true otherwise the modal will not close
                                return true;
                            }
                        }]
                }).data("kendoDialog");

                return {

                    open: function () {
                        return dialog.open();
                    },

                    close: function () {
                        return dialog.close();
                    },

                    getDialog: function () {
                        return dialog;
                    },

                    isHidden: function () {
                        return $(dialog.wrapper).is(":hidden");
                    }
                };
            }

            return {

                start: function () {

                    if (!instance) {
                        instance = init();
                    }

                    return instance;
                }

            };
        })();

        function logOut() {
            // Initialize or Start LogoutScripts
            var logoutDialog = LogOutScripts.start();
            if (logoutDialog != null) {
                if (logoutDialog.isHidden()) {
                    logoutDialog.open();
                }
            }
            
        }
    </script>
</body>

</html>

templates/base_bg.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    {% include '_head.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">
    <link rel="icon" href="{% static 'images/vw.png' %}" type="image/png" sizes="16x16">

    {% if not user.is_authenticated %}
    <style>
        @media (max-width: 991px) {
            #navbarSupportedContent {
                margin-top: 13.6em;
            }
        }
    </style>
    {% endif %}
</head>

<body>
    <div class="container-fluid px-0" style="background-color: #00AC46;">
        <!-- Top Navbar -->
        <nav class="navbar navbar-expand-lg mx-0 mt-0 px-4 pt-3">
            <a class="navbar-brand ml-2 mr-2" href="{% url 'users:list-all' %}"><img src="{% static 'images/vorwerk.png' %}" alt="" style="width: 50%"></a>
             {% if user.is_authenticated %}
                 <a class="mr-1 ml-auto d-lg-none" href="{% url 'users:profile' %}">
                     <img class="rounded-circle p-1" style="width: 35px; height: 35px;"
                             src="{% static 'images/smiley.png' %}">
                 </a>
             {% endif %}
             <button class="btn navbar-toggler mr-2" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                 <i class="fas fa-bars"></i>
             </button>
            
            <div class="collapse navbar-collapse nav justify-content-lg-center flex-column flex-lg-row p-3 p-lg-0" id="navbarSupportedContent" {% if user.is_authenticated %} style="margin-right: 4rem;" {% else %}style="margin-right: 12rem;" {% endif %}>
                {% if user.is_authenticated %}
                <li class="nav-item menu-item mx-lg-1 mx-xl-4">
                    <a class="nav-link" href="{% url 'users:list' request.user.id %}">Participações</a>
                </li>
                {% else %}
                <li class="nav-item menu-item mx-lg-1 mx-xl-4">
                    <a class="nav-link" href="{% url 'users:list-all' %}">Participações</a>
                </li>
                <li class="menu-user d-block d-lg-none">
                    <hr class="d-lg-none" style="border-top: 1px solid white;">
                    <!-- <button onclick="logOut()" class="btn-rev btn-md mr-1"
                        style="padding: 0.5rem 1rem;"><i class="fas fa-power-off"></i>&nbsp; Logout
                    </button> -->
                    <a href="{% url 'users:login' %}" class="nav-link">Iniciar Sessão</a>
                </li>
                {% endif %}
                {% if user.is_authenticated %}
                <!-- <li class="nav-item menu-item mx-lg-1 mx-xl-4">
                    <a class="nav-link" href="{% url 'users:upload' %}">Participar</a>
                </li> -->
                <li class="menu-user d-block d-lg-none">
                    <hr class="d-lg-none" style="border-top: 1px solid white;">
                    <!-- <button onclick="logOut()" class="btn-rev btn-md mr-1"
                        style="padding: 0.5rem 1rem;"><i class="fas fa-power-off"></i>&nbsp; Logout
                    </button> -->
                    <a href="{% url 'users:logout' %}" class="btn-rev btn-md mr-1" style="padding: 0.5rem 1rem;"><i class="fas fa-power-off"></i>&nbsp; Logout</a>
                </li>
                {% endif %}
            </div>
            
            {% if user.is_authenticated %}
            <a class="d-none d-lg-inline-block px-3 py-2 menu-user" href="{% url 'users:profile' %}">
                <img class="rounded-circle p-1" src="{% static 'images/smiley.png' %}">{{ user.username }}
            </a>
            <a class="btn btn-md mr-2 d-none d-lg-inline-block" style="padding-left: 12px; padding-right: 12px;" href="{% url 'users:logout' %}"><i class="fas fa-power-off"></i></a>
            {% else %}
            <a class="btn btn-md mr-2 d-none d-lg-inline-block" style="padding-left: 12px; padding-right: 12px;" href="{% url 'users:login' %}"><i class="fas fa-user"></i></a>
            <!-- <button onclick="logOut()" class="btn btn-md mr-2 d-none d-lg-inline-block" style="padding-left: 12px; padding-right: 12px;"><i class="fas fa-power-off"></i></button> -->
            {% endif %}
        </nav>

        <!-- Page Content  -->
        <div id="content">
            <div>
                {% for message in messages %}
                <div class="text-center mt-4 alert alert-{{ message.tags }}">
                    <i style="font-size: 20px;" class="fas fa-exclamation-circle"></i>
                    {{ message }}
                </div>
                {% endfor %}
                {% block content %}{% endblock %}
            </div>
        </div> 
        
        <!-- Footer d-none d-sm-none d-md-block  -->
        <div class="w-100 footer" style="font-size: 12px;">
            <div class="row p-4 m-0 text-center text-md-left" style="background-color: #d9d9d9;">
                <div class="col-12 col-md-3 mt-1">
                    <h6><a href="https://www.vorwerk.com/pt/pt/c/home/geral/termos-e-condicoes" target="_blank">Termos e Condições</a></h6>
                </div>
                <div class="col-12 col-md-3 mt-1">
                    <h6><a href="https://www.vorwerk.com/pt/pt/c/dam-home/downloads/regulamentos-passatempos/Regulamento-desafio-viagem-a-fabrica-2023.pdf" target="_blank">Regulamento</a></h6>
                </div>
                <div class="col-12 col-md-3 mt-1 px-0">
                    <h6>
                        <a href="https://www.vorwerk.com/pt/pt/c/home/geral/politica-de-privacidade" target="_blank">Política de privacidade</a>
                    </h6>
                </div>
                <div class="col-12 col-md-3 mt-4 mt-md-0">
                    <div class="socialmedia d-flex justify-content-around">
                        <a href="https://www.facebook.com/BimbyPortugal?fref=ts" target="_blank"><i class="fab fa-facebook"></i></a>
                        <a href="https://www.instagram.com/bimbyportugal/" target="_blank"><i class="fab fa-instagram"></i></a>
                        <a href="https://www.youtube.com/channel/UCCsNIGpKCR5XfNoYbiZi30g" target="_blank"><i class="fab fa-youtube"></i></a>
                        <a href="https://www.pinterest.pt/bimbyportugal/?eq=bimby&etslf=2543" target="_blank"><i class="fab fa-pinterest"></i></a>
                    </div>
                </div>
            </div>
            <div class="row p-1 m-0" style="background-color: rgb(162, 161, 161);">
                <div class="col mx-auto text-center">
                    <a href="https://qloudyx.pt" target="_blank"> &#169; {% now "Y" %}, eXcellerated by qloudyx.</a>
                </div>
            </div>
        </div>
        
        
    </div>
    {% include '_footer.html' %}
    <script id="jsLogoutTemplate" type="text/x-kendo-template">
        <div>
            <p>{{ user.username }}, pretende terminar sessão?</p>
        </div>
    </script>
    <script>
        var LogOutScripts = (function () {
            // Instance stores a reference to the LogOutScripts
            var instance;
            // Dialog object
            var dialog = $("<div />");

            function init() {
                dialog = dialog.kendoDialog({
                    title: "Terminar sessão",
                    content: kendo.template($("#jsLogoutTemplate").html()),
                    closable: false,
                    buttonLayout: "normal",
                    actions: [
                        {
                            text: "Sim",
                            action: function (e) {
                                window.location.href = "{% url 'users:logout' %}";
                                return true;
                            }
                        },
                        {
                            text: "Não",
                            primary: true,
                            action: function (e) {
                                // Do something...
                                // We must return true otherwise the modal will not close
                                return true;
                            }
                        }]
                }).data("kendoDialog");

                return {

                    open: function () {
                        return dialog.open();
                    },

                    close: function () {
                        return dialog.close();
                    },

                    getDialog: function () {
                        return dialog;
                    },

                    isHidden: function () {
                        return $(dialog.wrapper).is(":hidden");
                    }
                };
            }

            return {

                start: function () {

                    if (!instance) {
                        instance = init();
                    }

                    return instance;
                }

            };
        })();

        function logOut() {
            // Initialize or Start LogoutScripts
            var logoutDialog = LogOutScripts.start();
            if (logoutDialog != null) {
                if (logoutDialog.isHidden()) {
                    logoutDialog.open();
                }
            }
            
        }
    </script>
</body>

</html>

templates/base_logout.html
{% load static %}

<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.13.0/css/all.min.css" rel="stylesheet">

    <link rel="stylesheet" type="text/css" href="{% static 'css/base_logout.css' %}">

    {% if title %}
        <title>Vorwerk - {{ title }}</title>
    {% else %}
        <title>Vorwerk</title>
    {% endif %}
    <link rel="icon" href="{% static 'images/vorwerk.png' %}" type="image/png" sizes="16x16">
</head>
    <body>
        <header class="site-header">
            <nav class="navbar navbar-expand-md navbar-dark bg-steel fixed-top">
                <div class="container">
                    <a style="color: black;" class="navbar-brand mr-4" href="{% url 'users:login' %}">
                        APP
                    </a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarToggle" aria-controls="navbarToggle" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="collapse navbar-collapse" id="navbarToggle">
                        <div class="navbar-nav mr-auto">

                        </div>
                        <!-- Navbar Right Side -->

                    </div>
                </div>
            </nav>
        </header>
        <main role="main" class="container" style="padding-top: 20px;">
            <div class="row align-items-center">
                <div class="col-xl-12 col-lg-12 col-md-12">
                    {% for message in messages %}
                        <div class="alert alert-{{ message.tags }}">
                            {{ message }}
                        </div>
                    {% endfor %}
                    {% block content %}{% endblock %}
                </div>
            </div>
        </main>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
    </body>
</html>

templates/base_popup.html
{% load static %}
{% load crispy_forms_tags %}



<!DOCTYPE html>
<html>
<head>
    {% include '_head.html' %}
    <link rel="stylesheet" type="text/css" href="{% static 'css/base.css' %}">    
</head>
<body>
    <div class="content-section">
        <form method="post">{% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <button class="btn" type="submit">Guardar</button>
            </div>
        </form>
    </div>
    {% block specific %}{% endblock %}
    {% include '_footer.html' %}
</body>